# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://jpanther.github.io/congo/docs/getting-started/

# baseURL = "https://hugo-blog-bdt.pages.dev/"
baseURL = "https://hugo-blog-bdt.pages.dev/"
languageCode = "zh-Hans"
defaultContentLanguage = "zh-Hans"
defaultContentLanguageInSubdir = false
timeZone = "Asia/Shanghai"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[frontmatter]
format = "yaml"
# 自动日期填充配置
# date: 文章发布时间 - 优先使用front matter中的date，否则使用文件修改时间
date = ["date", ":fileModTime"]
# lastmod: 最后修改时间 - 优先使用front matter设置，否则使用文件修改时间
lastmod = ["lastmod", ":fileModTime"]

[[cascade]]
isCJKLanguage = true
_target.lang = "zh-Hans"

[outputs]
home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true
