languageCode = "zh-Hans"
languageName = "简体中文"
weight = 1
contentDir = "content"

title = "小萧的博客"

[params.author]
name = "小萧"
image = "img/author.webp"
headline = "知行合一，日拱一卒"
bio = "知行合一，日拱一卒"
links = [
    { email = "1454097327@qq.com" },
    { github = "https://github.com/xiao821" },
    { linuxdo = "https://linux.do/u/xiaoss12138/activity" }
]